### PR TITLE
Improve the performance

### PR DESCRIPTION
**Pull request by GiggleLiu**
The performance can be improved a lot by writing the loops explicitly. These improvements are useful in my friend's project. @jlbosse Do you have time to get this PR reviewed?

### CODE REVIEW

**Comment by jlbosse** [comment]
This looks good! I homogenized the formatting a bit, but didn't make any semantical changes. Before I merge this: Is `SparseArrays` still needed as a dependency, or has it been completely replaced with `LuxurySparse.SparseMatrixCOO`? If the latter, I would remove it from the Project.toml and also remove the SparseMatrixCSC methods of fast_add! and fast_overlap!.

**Comment by GiggleLiu** [comment]
Good point, I just removed SparseArrays from the dependency.

**Comment by GiggleLiu** [comment]
@jlbosse The CI failure seems to be irrelevant to this PR.

**Review by jlbosse — APPROVED** [review]
LGTM

**Comment by jlbosse** [comment]
Thanks for this! I merged and released a new version, so once https://github.com/JuliaRegistries/General/pull/115689 is merged you should be able to get the new version from the General registry

**Comment by GiggleLiu** [comment]
Cheers!

**Pull request merged**
